function nmpc = build_basic_nmpc(varargin)
    % Factory used across tests. Returns a 2D linear stable NMPC with sensible
    % defaults; any field can be overridden via name=value pairs.
    %
    %   nmpc = build_basic_nmpc(P=eye(2), soft_mask=[true false]);

    %% Defaults
    nx = 2;
    nu = 2;
    p  = 10;
    m  = 3;
    Ts = 0.1;

    defaults = struct( ...
        'f',     @toy_model, ...
        'nx',    nx, ...
        'nu',    nu, ...
        'Ts',    Ts, ...
        'p',     p, ...
        'm',     m, ...
        'y_sp',  [1 2], ...
        'u_sp',  [0 0], ...
        'Q',     diag([10 10]), ...
        'R',     diag([0.1 0.1]), ...
        'Ymin',  [-10 -10], ...
        'Ymax',  [ 10  10], ...
        'umin',  [-5  -5], ...
        'umax',  [ 5   5]);

    %% Apply overrides
    overrides = struct(varargin{:});
    fn = fieldnames(overrides);
    for k = 1 : numel(fn)
        defaults.(fn{k}) = overrides.(fn{k});
    end

    %% Build
    args = namedargs2cell(defaults);
    nmpc = NMPC(args{:});
end

function dx = toy_model(x, u)
    % 2D decoupled stable LTI:  xdot = A x + B u, A = diag(-1,-2), B = I
    dx = [-x(1) + u(1), -2*x(2) + u(2)];
end
