"""Parse the phi(z) surrogate vintage records into a flat CSV.

Auto-discovers every case subfolder under results/ (any directory that
contains a results.csv), reads its registry/vintages/vintage_*.json, and
writes one row per vintage to <storage>/surrogate_vintages.csv.

It also refreshes cases.txt with the discovered folder names, so the MATLAB
step (initial_preprocessing.m) picks up new cases with no manual editing.
Case ids are the folder names as-is; no renaming required.

Each vintage governs a block of BO iterations (governs_iterations), so the fit
wall time is a property of the vintage, not of a single evaluation.

Usage:
    python parse_registry.py                          # discover + do every case
    python parse_registry.py --cases results_case1    # pin an explicit subset
"""

import argparse
import csv
import glob
import json
import os
import re

COLUMNS = [
    "case", "vintage", "created_at", "gov_iter_start", "gov_iter_end",
    "n_doe_rows", "n_opt_rows_used", "n_runs_used", "n_samples",
    "SSE_a", "SSE_b", "SSE_lambda", "SSE_loss",
    "SSdU_a", "SSdU_b", "SSdU_lambda", "SSdU_loss",
    "fit_wall_s", "SSE_fit_wall_s", "SSdU_fit_wall_s",
]


def discover_cases(results_root):
    """Every subfolder of results_root that holds a results.csv, natural-sorted."""
    names = []
    for name in sorted(os.listdir(results_root)):
        d = os.path.join(results_root, name)
        if os.path.isdir(d) and os.path.exists(os.path.join(d, "results.csv")):
            names.append(name)

    def key(n):
        m = re.search(r"(\d+)$", n)          # trailing number -> numeric order
        return (0, int(m.group(1))) if m else (1, n)

    return sorted(names, key=key)


def write_cases_file(path, cases):
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("# Auto-generated by parse_registry.py: case subfolders under results/.\n")
        fh.write("# initial_preprocessing.m reads this. Re-run the parser to refresh.\n")
        for c in cases:
            fh.write(c + "\n")


def _governs(ctx):
    gi = ctx.get("governs_iterations") or [None, None]
    start = gi[0] if len(gi) > 0 else None
    end = gi[1] if len(gi) > 1 else None
    return start, end


def parse_vintage(case, path):
    with open(path, "r", encoding="utf-8") as fh:
        d = json.load(fh)
    ctx = d.get("context", {})
    tgt = d.get("targets", {})
    sse = tgt.get("SSE", {})
    ssdu = tgt.get("SSdU", {})
    wall = ctx.get("wall_s", {}).get("per_target", {})
    start, end = _governs(ctx)
    return {
        "case": case,
        "vintage": d.get("vintage"),
        "created_at": d.get("created_at"),
        "gov_iter_start": start,
        "gov_iter_end": end,
        "n_doe_rows": ctx.get("n_doe_rows"),
        "n_opt_rows_used": ctx.get("n_opt_rows_used"),
        "n_runs_used": sse.get("n_runs_used"),
        "n_samples": sse.get("n_samples"),
        "SSE_a": sse.get("a"),
        "SSE_b": sse.get("b"),
        "SSE_lambda": sse.get("lam"),
        "SSE_loss": sse.get("loss"),
        "SSdU_a": ssdu.get("a"),
        "SSdU_b": ssdu.get("b"),
        "SSdU_lambda": ssdu.get("lam"),
        "SSdU_loss": ssdu.get("loss"),
        "fit_wall_s": ctx.get("fit_wall_s"),
        "SSE_fit_wall_s": wall.get("SSE", {}).get("total"),
        "SSdU_fit_wall_s": wall.get("SSdU", {}).get("total"),
    }


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(here)              # Result analysis -> repo root
    default_storage = os.path.join(here, "storage")

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--cases", nargs="+", default=None,
                    help="Pin an explicit set of case subfolders (default: discover all).")
    ap.add_argument("--cases-file", default=os.path.join(here, "cases.txt"))
    ap.add_argument("--no-write-cases", action="store_true",
                    help="Do not refresh cases.txt.")
    ap.add_argument("--results-root", default=os.path.join(repo_root, "results"))
    ap.add_argument("--storage", default=default_storage)
    args = ap.parse_args()

    cases = args.cases if args.cases else discover_cases(args.results_root)
    if not cases:
        raise SystemExit(f"No case subfolders (with results.csv) found under {args.results_root}")
    if not args.no_write_cases:
        write_cases_file(args.cases_file, cases)

    os.makedirs(args.storage, exist_ok=True)
    rows = []
    for case in cases:
        vdir = os.path.join(args.results_root, case, "registry", "vintages")
        files = sorted(glob.glob(os.path.join(vdir, "vintage_*.json")))
        if not files:
            print(f"  [warn] no vintage files under {vdir}")
            continue
        for f in files:
            rows.append(parse_vintage(case, f))
        print(f"  {case}: {len(files)} vintages")

    out_csv = os.path.join(args.storage, "surrogate_vintages.csv")
    with open(out_csv, "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=COLUMNS)
        w.writeheader()
        w.writerows(rows)
    print(f"Cases: {', '.join(cases)}")
    print(f"Wrote {len(rows)} rows -> {out_csv}")


if __name__ == "__main__":
    main()
